# Generated by Django 4.2.7 on 2023-11-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('photo_ava', models.ImageField(upload_to='photos/', verbose_name='Аватар профиля')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('description', models.TextField(verbose_name='О себе')),
                ('who_are_you', models.CharField(choices=[('E', 'Сотрудник'), ('S', 'Студент')], max_length=1, verbose_name='Студент или сотрудник')),
                ('level', models.SmallIntegerField(null=True, verbose_name='Курс')),
                ('education', models.CharField(max_length=20, null=True, verbose_name='Ступень образования')),
                ('faculty', models.CharField(max_length=100, null=True, verbose_name='Факультет')),
                ('program', models.CharField(max_length=100, null=True, verbose_name='Образовательная программа')),
                ('work', models.CharField(max_length=150, verbose_name='Работа')),
                ('year_start_work', models.DateField(verbose_name='Начало работы')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
