# Generated by Django 4.2.7 on 2023-11-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeetuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeetuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
