# Generated by Django 4.2.7 on 2023-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0002_homeetuser_is_staff_homeetuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
