# Generated by Django 4.2.7 on 2023-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0003_alter_homeetuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='year_start_work',
            field=models.DateField(null=True, verbose_name='Начало работы'),
        ),
    ]
