# Generated by Django 4.2.7 on 2023-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0005_alter_homeetuser_options_homeetuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
