# Generated by Django 4.2.7 on 2023-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0006_alter_homeetuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='education',
            field=models.CharField(choices=[('', 'Ступень образования'), ('bachelor', 'Бакалавриат'), ('magistracy', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=20, null=True, verbose_name='Ступень образования'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='faculty',
            field=models.CharField(choices=[('', 'Факультет'), ('MIEM', 'МИЭМ'), ('FKN', 'ФКН'), ('VSHB', 'ВШБ')], max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Complited', 'Уже окончил')], max_length=20, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='program',
            field=models.CharField(choices=[('', 'Образовательная программа'), ('IVT', 'ИВТ'), ('ITSS', 'ИТСС'), ('PM', 'ПМ')], max_length=100, null=True, verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Парень'), ('F', 'Девушка')], max_length=1, verbose_name='Пол'),
        ),
    ]
