# Generated by Django 4.2.7 on 2023-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0007_alter_homeetuser_education_alter_homeetuser_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeetuser',
            name='email',
        ),
        migrations.AddField(
            model_name='homeetuser',
            name='tg',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
