# Generated by Django 4.2.7 on 2023-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0008_remove_homeetuser_email_homeetuser_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='tg',
            field=models.CharField(max_length=50, unique=True, verbose_name='Электронная почта'),
        ),
    ]
