# Generated by Django 4.2.7 on 2023-11-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0010_alter_homeetuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
