# Generated by Django 4.2.7 on 2023-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0011_alter_homeetuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='education',
            field=models.CharField(blank=True, choices=[('', 'Ступень образования'), ('bachelor', 'Бакалавриат'), ('magistracy', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=20, null=True, verbose_name='Ступень образования'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='faculty',
            field=models.CharField(blank=True, choices=[('', 'Факультет'), ('MIEM', 'МИЭМ'), ('FKN', 'ФКН'), ('VSHB', 'ВШБ')], max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Complited', 'Уже окончил')], max_length=20, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='program',
            field=models.CharField(blank=True, choices=[('', 'Образовательная программа'), ('IVT', 'ИВТ'), ('ITSS', 'ИТСС'), ('PM', 'ПМ')], max_length=100, null=True, verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='tg',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ник в телеграме'),
        ),
        migrations.AlterField(
            model_name='homeetuser',
            name='year_start_work',
            field=models.DateField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
