# Generated by Django 4.2.7 on 2023-11-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhomeet', '0013_alter_homeetuser_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetuser',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('E', 'Сотрудник'), ('S', 'Студент')], max_length=1, null=True, verbose_name='Студент или сотрудник'),
        ),
    ]
