# Generated by Django 4.2.7 on 2023-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('sex', models.CharField(choices=[('M', 'Парень'), ('F', 'Девушка')], max_length=1, verbose_name='Пол')),
                ('tg', models.CharField(max_length=50, unique=True, verbose_name='Ник в телеграме')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('photo_ava', models.ImageField(upload_to='photos/', verbose_name='Аватар профиля')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('description', models.TextField(verbose_name='О себе')),
                ('who_are_you', models.CharField(blank=True, choices=[('E', 'Сотрудник'), ('S', 'Студент')], max_length=1, null=True, verbose_name='Студент или сотрудник')),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Complited', 'Уже окончил')], max_length=20, null=True, verbose_name='Курс')),
                ('education', models.CharField(blank=True, choices=[('', 'Ступень образования'), ('bachelor', 'Бакалавриат'), ('magistracy', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=20, null=True, verbose_name='Ступень образования')),
                ('faculty', models.CharField(blank=True, choices=[('', 'Факультет'), ('MIEM', 'МИЭМ'), ('FKN', 'ФКН'), ('VSHB', 'ВШБ')], max_length=100, null=True, verbose_name='Факультет')),
                ('program', models.CharField(blank=True, choices=[('', 'Образовательная программа'), ('IVT', 'ИВТ'), ('ITSS', 'ИТСС'), ('PM', 'ПМ')], max_length=100, null=True, verbose_name='Образовательная программа')),
                ('work', models.CharField(default='Не работаю', max_length=150, verbose_name='Работа')),
                ('year_start_work', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
