# Generated by Django 4.2.7 on 2023-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_start_work',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Начало работы'),
        ),
    ]
